### ISSUE TITLE
AttributeError during searching lyrics from QianQian

### ISSUE THREAD

**Issue by SimonIT** [antoncoding/spotify_lyric#1]
Executing these lines
https://github.com/antoncoding/spotify_lyric/blob/fb5366802bc36686aa798a4cb69f03255b7c97f7/QQParser.py#L80-L81

results in an Attribute Error:
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\193.5662.61\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\user\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\193.5662.61\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "spotify_lyric/QQParser.py", line 81, in <module>
    search_lyric_from_QianQian('Eric Chou','我愛過你')
  File "spotify_lyric/QQParser.py", line 65, in search_lyric_from_QianQian
    sid = getSongId(artist, song)
  File "spotify_lyric/QQParser.py", line 42, in getSongId
    results = html_code.find("div", {"class": "search-song-list song-list song-list-hook"}).find("ul").find_all("li")
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by antoncoding** [comment]
Thanks for the notification. 
QQ search has added some protection that blocks my script, I'll refactor my code a little bit later, I just bypassed QQ search for now.
